# Generated by Django 5.1.3 on 2024-12-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='menu_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.product')),
            ],
            options={
                'verbose_name': 'Produto no pedido',
                'verbose_name_plural': 'Produtos no pedido',
            },
        ),
    ]
